**Trimer Simulations**


    A(a)+B(a)<->A(a!1).B(a!1) G=-20000
    A(b)+C(b)<->A(b!1).C(b!1) G=-20000
    B(b)+C(a)<->B(b!1).C(a!1) G=-20000
    
Init Conc = 100

k = 1.0 

Yield = 84. 2 % 

C  :  tensor([-0.2014], dtype=torch.float64, grad_fn=<AddBackward0>)
B  :  tensor([-0.2014], dtype=torch.float64, grad_fn=<AddBackward0>)
A  :  tensor([-0.2014], dtype=torch.float64, grad_fn=<AddBackward0>)
AB  :  tensor([-0.1959], dtype=torch.float64, grad_fn=<AddBackward0>)
AC  :  tensor([-0.1959], dtype=torch.float64, grad_fn=<AddBackward0>)
BC  :  tensor([-0.1958], dtype=torch.float64, grad_fn=<AddBackward0>)
ABC  :  tensor([0.5932], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([ 0.3259,  0.3260,  0.3260,  0.3276,  0.3276,  0.3276, 99.0188],
       dtype=torch.float64, grad_fn=<MaxBackward2>)

k = 10.0

Yield = 71.3%

C  :  tensor([-8.8815], dtype=torch.float64, grad_fn=<AddBackward0>)
B  :  tensor([-8.8815], dtype=torch.float64, grad_fn=<AddBackward0>)
A  :  tensor([-8.8815], dtype=torch.float64, grad_fn=<AddBackward0>)
ABC  :  tensor([2.6630], dtype=torch.float64, grad_fn=<AddBackward0>)
AB  :  tensor([3.1093], dtype=torch.float64, grad_fn=<AddBackward0>)
AC  :  tensor([3.1093], dtype=torch.float64, grad_fn=<AddBackward0>)
BC  :  tensor([3.1093], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([  0.6538,   0.6538,   0.6538,   0.1257,   0.1257,   0.1257, 100.2993],
       dtype=torch.float64, grad_fn=<MaxBackward2>)

Optimized rates:
tensor([ 9.3500,  9.3500,  9.3500, 10.8006, 10.8006, 10.8006],
       dtype=torch.float64, requires_grad=True)

k = 100

yield on sim iteration 4999 was 69.0%

B  :  tensor([-44.4860], dtype=torch.float64, grad_fn=<AddBackward0>)
C  :  tensor([-44.4860], dtype=torch.float64, grad_fn=<AddBackward0>)
A  :  tensor([-44.4860], dtype=torch.float64, grad_fn=<AddBackward0>)
AC  :  tensor([14.6839], dtype=torch.float64, grad_fn=<AddBackward0>)
AB  :  tensor([14.6839], dtype=torch.float64, grad_fn=<AddBackward0>)
BC  :  tensor([14.6839], dtype=torch.float64, grad_fn=<AddBackward0>)
ABC  :  tensor([15.1183], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([  0.4495,   0.4495,   0.4495,   0.1095,   0.1095,   0.1095, 101.1377],
       dtype=torch.float64, grad_fn=<MaxBackward2>)

Optmized rates:
tensor([ 97.6182,  97.6182,  97.6182, 102.3641, 102.3641, 102.3641],
       dtype=torch.float64, requires_grad=True)

In [ ]:
k = 1000

yield on sim iteration 4998 was 79.1%

A  :  tensor([-933.0330], dtype=torch.float64, grad_fn=<AddBackward0>)
B  :  tensor([-933.0330], dtype=torch.float64, grad_fn=<AddBackward0>)
AC  :  tensor([-3.7564], dtype=torch.float64, grad_fn=<AddBackward0>)
BC  :  tensor([-3.7564], dtype=torch.float64, grad_fn=<AddBackward0>)
C  :  tensor([0.0037], dtype=torch.float64, grad_fn=<AddBackward0>)
ABC  :  tensor([7.5091], dtype=torch.float64, grad_fn=<AddBackward0>)
AB  :  tensor([929.2803], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([9.6666e-01, 9.6666e-01, 0.0000e+00, 3.2621e+00, 3.8687e-03, 3.8687e-03,
        1.1286e+02], dtype=torch.float64, grad_fn=<MaxBackward2>)
Optmized rates::
tensor([ 994.9978,  994.9978,  994.9978, 1004.9955, 1004.9955, 1004.9955],
       dtype=torch.float64, requires_grad=True)

In [ ]:
k = 10000

yield on sim iteration 4999 was 100.%

A  :  tensor([-499.8462], dtype=torch.float64, grad_fn=<AddBackward0>)
B  :  tensor([-499.8462], dtype=torch.float64, grad_fn=<AddBackward0>)
AC  :  tensor([-232.0795], dtype=torch.float64, grad_fn=<AddBackward0>)
BC  :  tensor([-232.0795], dtype=torch.float64, grad_fn=<AddBackward0>)
C  :  tensor([0.9751], dtype=torch.float64, grad_fn=<AddBackward0>)
AB  :  tensor([268.7417], dtype=torch.float64, grad_fn=<AddBackward0>)
ABC  :  tensor([463.1840], dtype=torch.float64, grad_fn=<AddBackward0>)

tensor([1.6381e-01, 1.6381e-01, 0.0000e+00, 0.0000e+00, 1.4182e-01, 1.4182e-01,
        2.4556e+03], dtype=torch.float64, grad_fn=<MaxBackward2>)

Optimized rates:
tensor([ 9995.0231,  9995.0231,  9995.0231, 10004.9780, 10004.9780, 10004.9780],
       dtype=torch.float64, requires_grad=True)

k = 0.1 

yield on sim iteration 4999 was 77.6%

C  :  tensor([-0.1076], dtype=torch.float64, grad_fn=<AddBackward0>)
A  :  tensor([-0.1076], dtype=torch.float64, grad_fn=<AddBackward0>)
B  :  tensor([-0.1076], dtype=torch.float64, grad_fn=<AddBackward0>)
AB  :  tensor([-0.1039], dtype=torch.float64, grad_fn=<AddBackward0>)
BC  :  tensor([-0.1039], dtype=torch.float64, grad_fn=<AddBackward0>)
AC  :  tensor([-0.1039], dtype=torch.float64, grad_fn=<AddBackward0>)
ABC  :  tensor([0.3155], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([ 0.3275,  0.3275,  0.3275,  0.3289,  0.3289,  0.3289, 99.0148],
       dtype=torch.float64, grad_fn=<MaxBackward2>)

 Parameter containing:
tensor([0.0114, 0.0114, 0.0114, 0.9764, 0.9764, 0.9764], dtype=torch.float64,
       requires_grad=True)

In [ ]:
k = 0.01

Yield = 75.3%

A  :  tensor([-0.0653], dtype=torch.float64, grad_fn=<AddBackward0>)
B  :  tensor([-0.0653], dtype=torch.float64, grad_fn=<AddBackward0>)
C  :  tensor([-0.0653], dtype=torch.float64, grad_fn=<AddBackward0>)
BC  :  tensor([-0.0619], dtype=torch.float64, grad_fn=<AddBackward0>)
AC  :  tensor([-0.0619], dtype=torch.float64, grad_fn=<AddBackward0>)
AB  :  tensor([-0.0619], dtype=torch.float64, grad_fn=<AddBackward0>)
ABC  :  tensor([0.1891], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([ 0.3297,  0.3297,  0.3297,  0.3306,  0.3306,  0.3306, 99.0092],
       dtype=torch.float64, grad_fn=<MaxBackward2>)
Parameter containing:
tensor([0.0104, 0.0104, 0.0104, 0.5785, 0.5785, 0.5785], dtype=torch.float64,
       requires_grad=True)


    A(a)+B(a)<->A(a!1).B(a!1) G=-20000
    A(b)+C(b)<->A(b!1).C(b!1) G=-10000
    B(b)+C(a)<->B(b!1).C(a!1) G=-20000
    
Init Conc = 100

In [ ]:
k = 1.0 

yield on sim iteration 4999 was 98.7%

C  :  tensor([-0.7012], dtype=torch.float64, grad_fn=<AddBackward0>)
A  :  tensor([-0.7012], dtype=torch.float64, grad_fn=<AddBackward0>)
AB  :  tensor([-0.4991], dtype=torch.float64, grad_fn=<AddBackward0>)
BC  :  tensor([-0.4991], dtype=torch.float64, grad_fn=<AddBackward0>)
B  :  tensor([-0.0002], dtype=torch.float64, grad_fn=<AddBackward0>)
AC  :  tensor([0.2019], dtype=torch.float64, grad_fn=<AddBackward0>)
ABC  :  tensor([0.9983], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([4.9702e-01, 7.0980e-03, 4.9702e-01, 5.9924e-01, 5.9669e-03, 5.9924e-01,
        9.9112e+01], dtype=torch.float64, grad_fn=<MaxBackward2>)
Parameter containing:
tensor([0.0226, 0.8179, 0.0226, 1.6472, 1.6769, 1.6769], dtype=torch.float64,
       requires_grad=True)


**Simulation Set 3**

    A(a)+B(a)<->A(a!1).B(a!1) G=-20000
    A(b)+C(b)<->A(b!1).C(b!1) G=-10000
    B(b)+C(a)<->B(b!1).C(a!1) G=-10000
    
Init Conc = 100

In [ ]:
k = 1.0 

yield on sim iteration 4999 was 73.9%

C  :  tensor([-1.6336], dtype=torch.float64, grad_fn=<AddBackward0>)
AB  :  tensor([-1.6168], dtype=torch.float64, grad_fn=<AddBackward0>)
A  :  tensor([-0.0084], dtype=torch.float64, grad_fn=<AddBackward0>)
B  :  tensor([-0.0084], dtype=torch.float64, grad_fn=<AddBackward0>)
BC  :  tensor([0.0084], dtype=torch.float64, grad_fn=<AddBackward0>)
AC  :  tensor([0.0084], dtype=torch.float64, grad_fn=<AddBackward0>)
ABC  :  tensor([1.6168], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([1.0999e-02, 1.0999e-02, 9.6096e-01, 9.5107e-01, 1.9350e-02, 1.9350e-02,
        1.0709e+02], dtype=torch.float64, grad_fn=<MaxBackward2>)
Parameter containing:
tensor([1.0644, 0.8116, 0.8116, 0.8326, 1.8006, 0.8326], dtype=torch.float64,
       requires_grad=True)