In [1]:
import torch

In [15]:
a = torch.zeros((5, 3)).double()
a = a + 5
a[2,:] = 2

In [12]:
b = torch.zeros((3)).double()
b =b +2
b[2] = 3
print(b)

tensor([2., 2., 3.], dtype=torch.float64)


In [16]:
c = torch.mul(a,b)
print(c)

tensor([[10., 10., 15.],
        [10., 10., 15.],
        [ 4.,  4.,  6.],
        [10., 10., 15.],
        [10., 10., 15.]], dtype=torch.float64)


In [17]:
d = a + b
print(d)

tensor([[7., 7., 8.],
        [7., 7., 8.],
        [4., 4., 5.],
        [7., 7., 8.],
        [7., 7., 8.]], dtype=torch.float64)
